
2019-10-06 23:05:02,091 INFO: errors [in /home/dharmy-ko/Desktop/projects/udacity/artist_bookings/starter_code/app.py:472]
2019-10-06 23:07:10,160 INFO: errors [in /home/dharmy-ko/Desktop/projects/udacity/artist_bookings/starter_code/app.py:472]
2019-10-06 23:07:18,861 INFO: errors [in /home/dharmy-ko/Desktop/projects/udacity/artist_bookings/starter_code/app.py:472]
2019-10-06 23:09:36,303 INFO: errors [in app.py:472]
2019-10-06 23:10:29,237 INFO: errors [in /home/dharmy-ko/Desktop/projects/udacity/artist_bookings/starter_code/app.py:472]
2019-10-06 23:11:11,435 INFO: errors [in /home/dharmy-ko/Desktop/projects/udacity/artist_bookings/starter_code/app.py:472]
2019-10-07 00:31:58,387 INFO: errors [in /home/dharmy-ko/Desktop/projects/udacity/artist_bookings/starter_code/app.py:498]
2019-10-07 11:00:26,159 INFO: errors [in /home/dharmy-ko/Desktop/projects/udacity/artist_bookings/starter_code/app.py:492]
2019-10-07 11:00:50,431 INFO: errors [in /home/dharmy-ko/Desktop/projects/udacity/artist_bookings/starter_code/app.py:492]
2019-10-07 11:02:25,272 INFO: errors [in /home/dharmy-ko/Desktop/projects/udacity/artist_bookings/starter_code/app.py:484]
2019-10-07 11:02:33,815 INFO: errors [in /home/dharmy-ko/Desktop/projects/udacity/artist_bookings/starter_code/app.py:484]
2019-10-07 11:06:59,425 INFO: errors [in /home/dharmy-ko/Desktop/projects/udacity/artist_bookings/starter_code/app.py:484]
2019-10-07 11:07:06,102 INFO: errors [in /home/dharmy-ko/Desktop/projects/udacity/artist_bookings/starter_code/app.py:484]
2019-10-07 17:29:44,769 INFO: errors [in app.py:484]
2019-10-07 17:30:16,151 ERROR: Exception on /artists/create [GET] [in /home/dharmy-ko/Desktop/projects/udacity/artist_bookings/env/lib/python3.6/site-packages/flask/app.py:1891]
Traceback (most recent call last):
  File "/home/dharmy-ko/Desktop/projects/udacity/artist_bookings/env/lib/python3.6/site-packages/flask/app.py", line 2446, in wsgi_app
    response = self.full_dispatch_request()
  File "/home/dharmy-ko/Desktop/projects/udacity/artist_bookings/env/lib/python3.6/site-packages/flask/app.py", line 1951, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/home/dharmy-ko/Desktop/projects/udacity/artist_bookings/env/lib/python3.6/site-packages/flask/app.py", line 1820, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "/home/dharmy-ko/Desktop/projects/udacity/artist_bookings/env/lib/python3.6/site-packages/flask/_compat.py", line 39, in reraise
    raise value
  File "/home/dharmy-ko/Desktop/projects/udacity/artist_bookings/env/lib/python3.6/site-packages/flask/app.py", line 1949, in full_dispatch_request
    rv = self.dispatch_request()
  File "/home/dharmy-ko/Desktop/projects/udacity/artist_bookings/env/lib/python3.6/site-packages/flask/app.py", line 1935, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "app.py", line 387, in create_artist_form
    form = ArtistForm()
NameError: name 'ArtistForm' is not defined
2019-10-07 17:46:53,349 INFO: errors [in /home/dharmy-ko/Desktop/projects/udacity/artist_bookings/starter_code/app.py:484]
2019-10-07 17:47:05,216 INFO: errors [in /home/dharmy-ko/Desktop/projects/udacity/artist_bookings/starter_code/app.py:484]
2019-10-07 18:32:16,936 INFO: errors [in /home/dharmy-ko/Desktop/projects/udacity/artist_bookings/starter_code/app.py:498]
2019-10-07 18:32:32,532 INFO: errors [in /home/dharmy-ko/Desktop/projects/udacity/artist_bookings/starter_code/app.py:498]
2019-10-07 18:33:56,253 INFO: errors [in /home/dharmy-ko/Desktop/projects/udacity/artist_bookings/starter_code/app.py:498]
2019-10-07 18:35:55,454 INFO: errors [in /home/dharmy-ko/Desktop/projects/udacity/artist_bookings/starter_code/app.py:498]
2019-10-07 18:36:05,701 INFO: errors [in /home/dharmy-ko/Desktop/projects/udacity/artist_bookings/starter_code/app.py:498]
2019-10-07 18:39:37,656 INFO: errors [in /home/dharmy-ko/Desktop/projects/udacity/artist_bookings/starter_code/app.py:498]
2019-10-07 18:39:45,031 INFO: errors [in /home/dharmy-ko/Desktop/projects/udacity/artist_bookings/starter_code/app.py:498]
2019-10-07 18:40:01,675 INFO: errors [in /home/dharmy-ko/Desktop/projects/udacity/artist_bookings/starter_code/app.py:498]
2019-10-08 01:26:46,255 INFO: errors [in /home/dharmy-ko/Desktop/projects/udacity/artist_bookings/starter_code/app.py:511]
2019-10-08 01:27:12,640 INFO: errors [in /home/dharmy-ko/Desktop/projects/udacity/artist_bookings/starter_code/app.py:511]
2019-10-08 19:05:13,523 INFO: errors [in /home/dharmy-ko/Desktop/projects/udacity/artist_bookings/starter_code/app.py:514]
2019-10-08 19:06:18,454 INFO: errors [in /home/dharmy-ko/Desktop/projects/udacity/artist_bookings/starter_code/app.py:514]
2019-10-08 19:06:52,790 INFO: errors [in /home/dharmy-ko/Desktop/projects/udacity/artist_bookings/starter_code/app.py:514]
2019-10-08 19:07:04,908 INFO: errors [in /home/dharmy-ko/Desktop/projects/udacity/artist_bookings/starter_code/app.py:514]
2019-10-08 19:08:43,812 INFO: errors [in /home/dharmy-ko/Desktop/projects/udacity/artist_bookings/starter_code/app.py:514]
2019-10-11 13:46:46,402 INFO: errors [in /home/dharmy-ko/Desktop/projects/udacity/artist_bookings/starter_code/app.py:551]
2019-10-11 13:47:02,024 ERROR: Exception on /artists [GET] [in /home/dharmy-ko/Desktop/projects/udacity/artist_bookings/env/lib/python3.6/site-packages/flask/app.py:1891]
Traceback (most recent call last):
  File "/home/dharmy-ko/Desktop/projects/udacity/artist_bookings/env/lib/python3.6/site-packages/sqlalchemy/engine/base.py", line 2275, in _wrap_pool_connect
    return fn()
  File "/home/dharmy-ko/Desktop/projects/udacity/artist_bookings/env/lib/python3.6/site-packages/sqlalchemy/pool/base.py", line 363, in connect
    return _ConnectionFairy._checkout(self)
  File "/home/dharmy-ko/Desktop/projects/udacity/artist_bookings/env/lib/python3.6/site-packages/sqlalchemy/pool/base.py", line 760, in _checkout
    fairy = _ConnectionRecord.checkout(pool)
  File "/home/dharmy-ko/Desktop/projects/udacity/artist_bookings/env/lib/python3.6/site-packages/sqlalchemy/pool/base.py", line 492, in checkout
    rec = pool._do_get()
  File "/home/dharmy-ko/Desktop/projects/udacity/artist_bookings/env/lib/python3.6/site-packages/sqlalchemy/pool/impl.py", line 139, in _do_get
    self._dec_overflow()
  File "/home/dharmy-ko/Desktop/projects/udacity/artist_bookings/env/lib/python3.6/site-packages/sqlalchemy/util/langhelpers.py", line 68, in __exit__
    compat.reraise(exc_type, exc_value, exc_tb)
  File "/home/dharmy-ko/Desktop/projects/udacity/artist_bookings/env/lib/python3.6/site-packages/sqlalchemy/util/compat.py", line 153, in reraise
    raise value
  File "/home/dharmy-ko/Desktop/projects/udacity/artist_bookings/env/lib/python3.6/site-packages/sqlalchemy/pool/impl.py", line 136, in _do_get
    return self._create_connection()
  File "/home/dharmy-ko/Desktop/projects/udacity/artist_bookings/env/lib/python3.6/site-packages/sqlalchemy/pool/base.py", line 308, in _create_connection
    return _ConnectionRecord(self)
  File "/home/dharmy-ko/Desktop/projects/udacity/artist_bookings/env/lib/python3.6/site-packages/sqlalchemy/pool/base.py", line 437, in __init__
    self.__connect(first_connect_check=True)
  File "/home/dharmy-ko/Desktop/projects/udacity/artist_bookings/env/lib/python3.6/site-packages/sqlalchemy/pool/base.py", line 639, in __connect
    connection = pool._invoke_creator(self)
  File "/home/dharmy-ko/Desktop/projects/udacity/artist_bookings/env/lib/python3.6/site-packages/sqlalchemy/engine/strategies.py", line 114, in connect
    return dialect.connect(*cargs, **cparams)
  File "/home/dharmy-ko/Desktop/projects/udacity/artist_bookings/env/lib/python3.6/site-packages/sqlalchemy/engine/default.py", line 453, in connect
    return self.dbapi.connect(*cargs, **cparams)
  File "/home/dharmy-ko/Desktop/projects/udacity/artist_bookings/env/lib/python3.6/site-packages/psycopg2/__init__.py", line 126, in connect
    conn = _connect(dsn, connection_factory=connection_factory, **kwasync)
psycopg2.OperationalError: FATAL:  database "fyyur" does not exist


The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/home/dharmy-ko/Desktop/projects/udacity/artist_bookings/env/lib/python3.6/site-packages/flask/app.py", line 2446, in wsgi_app
    response = self.full_dispatch_request()
  File "/home/dharmy-ko/Desktop/projects/udacity/artist_bookings/env/lib/python3.6/site-packages/flask/app.py", line 1951, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/home/dharmy-ko/Desktop/projects/udacity/artist_bookings/env/lib/python3.6/site-packages/flask/app.py", line 1820, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "/home/dharmy-ko/Desktop/projects/udacity/artist_bookings/env/lib/python3.6/site-packages/flask/_compat.py", line 39, in reraise
    raise value
  File "/home/dharmy-ko/Desktop/projects/udacity/artist_bookings/env/lib/python3.6/site-packages/flask/app.py", line 1949, in full_dispatch_request
    rv = self.dispatch_request()
  File "/home/dharmy-ko/Desktop/projects/udacity/artist_bookings/env/lib/python3.6/site-packages/flask/app.py", line 1935, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/home/dharmy-ko/Desktop/projects/udacity/artist_bookings/starter_code/app.py", line 260, in artists
    data = Artist.query.all()
  File "/home/dharmy-ko/Desktop/projects/udacity/artist_bookings/env/lib/python3.6/site-packages/sqlalchemy/orm/query.py", line 3178, in all
    return list(self)
  File "/home/dharmy-ko/Desktop/projects/udacity/artist_bookings/env/lib/python3.6/site-packages/sqlalchemy/orm/query.py", line 3334, in __iter__
    return self._execute_and_instances(context)
  File "/home/dharmy-ko/Desktop/projects/udacity/artist_bookings/env/lib/python3.6/site-packages/sqlalchemy/orm/query.py", line 3356, in _execute_and_instances
    querycontext, self._connection_from_session, close_with_result=True
  File "/home/dharmy-ko/Desktop/projects/udacity/artist_bookings/env/lib/python3.6/site-packages/sqlalchemy/orm/query.py", line 3371, in _get_bind_args
    mapper=self._bind_mapper(), clause=querycontext.statement, **kw
  File "/home/dharmy-ko/Desktop/projects/udacity/artist_bookings/env/lib/python3.6/site-packages/sqlalchemy/orm/query.py", line 3349, in _connection_from_session
    conn = self.session.connection(**kw)
  File "/home/dharmy-ko/Desktop/projects/udacity/artist_bookings/env/lib/python3.6/site-packages/sqlalchemy/orm/session.py", line 1124, in connection
    execution_options=execution_options,
  File "/home/dharmy-ko/Desktop/projects/udacity/artist_bookings/env/lib/python3.6/site-packages/sqlalchemy/orm/session.py", line 1130, in _connection_for_bind
    engine, execution_options
  File "/home/dharmy-ko/Desktop/projects/udacity/artist_bookings/env/lib/python3.6/site-packages/sqlalchemy/orm/session.py", line 431, in _connection_for_bind
    conn = bind._contextual_connect()
  File "/home/dharmy-ko/Desktop/projects/udacity/artist_bookings/env/lib/python3.6/site-packages/sqlalchemy/engine/base.py", line 2239, in _contextual_connect
    self._wrap_pool_connect(self.pool.connect, None),
  File "/home/dharmy-ko/Desktop/projects/udacity/artist_bookings/env/lib/python3.6/site-packages/sqlalchemy/engine/base.py", line 2279, in _wrap_pool_connect
    e, dialect, self
  File "/home/dharmy-ko/Desktop/projects/udacity/artist_bookings/env/lib/python3.6/site-packages/sqlalchemy/engine/base.py", line 1544, in _handle_dbapi_exception_noconnection
    util.raise_from_cause(sqlalchemy_exception, exc_info)
  File "/home/dharmy-ko/Desktop/projects/udacity/artist_bookings/env/lib/python3.6/site-packages/sqlalchemy/util/compat.py", line 398, in raise_from_cause
    reraise(type(exception), exception, tb=exc_tb, cause=cause)
  File "/home/dharmy-ko/Desktop/projects/udacity/artist_bookings/env/lib/python3.6/site-packages/sqlalchemy/util/compat.py", line 152, in reraise
    raise value.with_traceback(tb)
  File "/home/dharmy-ko/Desktop/projects/udacity/artist_bookings/env/lib/python3.6/site-packages/sqlalchemy/engine/base.py", line 2275, in _wrap_pool_connect
    return fn()
  File "/home/dharmy-ko/Desktop/projects/udacity/artist_bookings/env/lib/python3.6/site-packages/sqlalchemy/pool/base.py", line 363, in connect
    return _ConnectionFairy._checkout(self)
  File "/home/dharmy-ko/Desktop/projects/udacity/artist_bookings/env/lib/python3.6/site-packages/sqlalchemy/pool/base.py", line 760, in _checkout
    fairy = _ConnectionRecord.checkout(pool)
  File "/home/dharmy-ko/Desktop/projects/udacity/artist_bookings/env/lib/python3.6/site-packages/sqlalchemy/pool/base.py", line 492, in checkout
    rec = pool._do_get()
  File "/home/dharmy-ko/Desktop/projects/udacity/artist_bookings/env/lib/python3.6/site-packages/sqlalchemy/pool/impl.py", line 139, in _do_get
    self._dec_overflow()
  File "/home/dharmy-ko/Desktop/projects/udacity/artist_bookings/env/lib/python3.6/site-packages/sqlalchemy/util/langhelpers.py", line 68, in __exit__
    compat.reraise(exc_type, exc_value, exc_tb)
  File "/home/dharmy-ko/Desktop/projects/udacity/artist_bookings/env/lib/python3.6/site-packages/sqlalchemy/util/compat.py", line 153, in reraise
    raise value
  File "/home/dharmy-ko/Desktop/projects/udacity/artist_bookings/env/lib/python3.6/site-packages/sqlalchemy/pool/impl.py", line 136, in _do_get
    return self._create_connection()
  File "/home/dharmy-ko/Desktop/projects/udacity/artist_bookings/env/lib/python3.6/site-packages/sqlalchemy/pool/base.py", line 308, in _create_connection
    return _ConnectionRecord(self)
  File "/home/dharmy-ko/Desktop/projects/udacity/artist_bookings/env/lib/python3.6/site-packages/sqlalchemy/pool/base.py", line 437, in __init__
    self.__connect(first_connect_check=True)
  File "/home/dharmy-ko/Desktop/projects/udacity/artist_bookings/env/lib/python3.6/site-packages/sqlalchemy/pool/base.py", line 639, in __connect
    connection = pool._invoke_creator(self)
  File "/home/dharmy-ko/Desktop/projects/udacity/artist_bookings/env/lib/python3.6/site-packages/sqlalchemy/engine/strategies.py", line 114, in connect
    return dialect.connect(*cargs, **cparams)
  File "/home/dharmy-ko/Desktop/projects/udacity/artist_bookings/env/lib/python3.6/site-packages/sqlalchemy/engine/default.py", line 453, in connect
    return self.dbapi.connect(*cargs, **cparams)
  File "/home/dharmy-ko/Desktop/projects/udacity/artist_bookings/env/lib/python3.6/site-packages/psycopg2/__init__.py", line 126, in connect
    conn = _connect(dsn, connection_factory=connection_factory, **kwasync)
sqlalchemy.exc.OperationalError: (psycopg2.OperationalError) FATAL:  database "fyyur" does not exist

(Background on this error at: http://sqlalche.me/e/e3q8)
2019-10-11 13:47:06,958 ERROR: Exception on /shows [GET] [in /home/dharmy-ko/Desktop/projects/udacity/artist_bookings/env/lib/python3.6/site-packages/flask/app.py:1891]
Traceback (most recent call last):
  File "/home/dharmy-ko/Desktop/projects/udacity/artist_bookings/env/lib/python3.6/site-packages/sqlalchemy/engine/base.py", line 2275, in _wrap_pool_connect
    return fn()
  File "/home/dharmy-ko/Desktop/projects/udacity/artist_bookings/env/lib/python3.6/site-packages/sqlalchemy/pool/base.py", line 363, in connect
    return _ConnectionFairy._checkout(self)
  File "/home/dharmy-ko/Desktop/projects/udacity/artist_bookings/env/lib/python3.6/site-packages/sqlalchemy/pool/base.py", line 760, in _checkout
    fairy = _ConnectionRecord.checkout(pool)
  File "/home/dharmy-ko/Desktop/projects/udacity/artist_bookings/env/lib/python3.6/site-packages/sqlalchemy/pool/base.py", line 492, in checkout
    rec = pool._do_get()
  File "/home/dharmy-ko/Desktop/projects/udacity/artist_bookings/env/lib/python3.6/site-packages/sqlalchemy/pool/impl.py", line 139, in _do_get
    self._dec_overflow()
  File "/home/dharmy-ko/Desktop/projects/udacity/artist_bookings/env/lib/python3.6/site-packages/sqlalchemy/util/langhelpers.py", line 68, in __exit__
    compat.reraise(exc_type, exc_value, exc_tb)
  File "/home/dharmy-ko/Desktop/projects/udacity/artist_bookings/env/lib/python3.6/site-packages/sqlalchemy/util/compat.py", line 153, in reraise
    raise value
  File "/home/dharmy-ko/Desktop/projects/udacity/artist_bookings/env/lib/python3.6/site-packages/sqlalchemy/pool/impl.py", line 136, in _do_get
    return self._create_connection()
  File "/home/dharmy-ko/Desktop/projects/udacity/artist_bookings/env/lib/python3.6/site-packages/sqlalchemy/pool/base.py", line 308, in _create_connection
    return _ConnectionRecord(self)
  File "/home/dharmy-ko/Desktop/projects/udacity/artist_bookings/env/lib/python3.6/site-packages/sqlalchemy/pool/base.py", line 437, in __init__
    self.__connect(first_connect_check=True)
  File "/home/dharmy-ko/Desktop/projects/udacity/artist_bookings/env/lib/python3.6/site-packages/sqlalchemy/pool/base.py", line 639, in __connect
    connection = pool._invoke_creator(self)
  File "/home/dharmy-ko/Desktop/projects/udacity/artist_bookings/env/lib/python3.6/site-packages/sqlalchemy/engine/strategies.py", line 114, in connect
    return dialect.connect(*cargs, **cparams)
  File "/home/dharmy-ko/Desktop/projects/udacity/artist_bookings/env/lib/python3.6/site-packages/sqlalchemy/engine/default.py", line 453, in connect
    return self.dbapi.connect(*cargs, **cparams)
  File "/home/dharmy-ko/Desktop/projects/udacity/artist_bookings/env/lib/python3.6/site-packages/psycopg2/__init__.py", line 126, in connect
    conn = _connect(dsn, connection_factory=connection_factory, **kwasync)
psycopg2.OperationalError: FATAL:  database "fyyur" does not exist


The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/home/dharmy-ko/Desktop/projects/udacity/artist_bookings/env/lib/python3.6/site-packages/flask/app.py", line 2446, in wsgi_app
    response = self.full_dispatch_request()
  File "/home/dharmy-ko/Desktop/projects/udacity/artist_bookings/env/lib/python3.6/site-packages/flask/app.py", line 1951, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/home/dharmy-ko/Desktop/projects/udacity/artist_bookings/env/lib/python3.6/site-packages/flask/app.py", line 1820, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "/home/dharmy-ko/Desktop/projects/udacity/artist_bookings/env/lib/python3.6/site-packages/flask/_compat.py", line 39, in reraise
    raise value
  File "/home/dharmy-ko/Desktop/projects/udacity/artist_bookings/env/lib/python3.6/site-packages/flask/app.py", line 1949, in full_dispatch_request
    rv = self.dispatch_request()
  File "/home/dharmy-ko/Desktop/projects/udacity/artist_bookings/env/lib/python3.6/site-packages/flask/app.py", line 1935, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/home/dharmy-ko/Desktop/projects/udacity/artist_bookings/starter_code/app.py", line 507, in shows
    shows = Show.query.all()
  File "/home/dharmy-ko/Desktop/projects/udacity/artist_bookings/env/lib/python3.6/site-packages/sqlalchemy/orm/query.py", line 3178, in all
    return list(self)
  File "/home/dharmy-ko/Desktop/projects/udacity/artist_bookings/env/lib/python3.6/site-packages/sqlalchemy/orm/query.py", line 3334, in __iter__
    return self._execute_and_instances(context)
  File "/home/dharmy-ko/Desktop/projects/udacity/artist_bookings/env/lib/python3.6/site-packages/sqlalchemy/orm/query.py", line 3356, in _execute_and_instances
    querycontext, self._connection_from_session, close_with_result=True
  File "/home/dharmy-ko/Desktop/projects/udacity/artist_bookings/env/lib/python3.6/site-packages/sqlalchemy/orm/query.py", line 3371, in _get_bind_args
    mapper=self._bind_mapper(), clause=querycontext.statement, **kw
  File "/home/dharmy-ko/Desktop/projects/udacity/artist_bookings/env/lib/python3.6/site-packages/sqlalchemy/orm/query.py", line 3349, in _connection_from_session
    conn = self.session.connection(**kw)
  File "/home/dharmy-ko/Desktop/projects/udacity/artist_bookings/env/lib/python3.6/site-packages/sqlalchemy/orm/session.py", line 1124, in connection
    execution_options=execution_options,
  File "/home/dharmy-ko/Desktop/projects/udacity/artist_bookings/env/lib/python3.6/site-packages/sqlalchemy/orm/session.py", line 1130, in _connection_for_bind
    engine, execution_options
  File "/home/dharmy-ko/Desktop/projects/udacity/artist_bookings/env/lib/python3.6/site-packages/sqlalchemy/orm/session.py", line 431, in _connection_for_bind
    conn = bind._contextual_connect()
  File "/home/dharmy-ko/Desktop/projects/udacity/artist_bookings/env/lib/python3.6/site-packages/sqlalchemy/engine/base.py", line 2239, in _contextual_connect
    self._wrap_pool_connect(self.pool.connect, None),
  File "/home/dharmy-ko/Desktop/projects/udacity/artist_bookings/env/lib/python3.6/site-packages/sqlalchemy/engine/base.py", line 2279, in _wrap_pool_connect
    e, dialect, self
  File "/home/dharmy-ko/Desktop/projects/udacity/artist_bookings/env/lib/python3.6/site-packages/sqlalchemy/engine/base.py", line 1544, in _handle_dbapi_exception_noconnection
    util.raise_from_cause(sqlalchemy_exception, exc_info)
  File "/home/dharmy-ko/Desktop/projects/udacity/artist_bookings/env/lib/python3.6/site-packages/sqlalchemy/util/compat.py", line 398, in raise_from_cause
    reraise(type(exception), exception, tb=exc_tb, cause=cause)
  File "/home/dharmy-ko/Desktop/projects/udacity/artist_bookings/env/lib/python3.6/site-packages/sqlalchemy/util/compat.py", line 152, in reraise
    raise value.with_traceback(tb)
  File "/home/dharmy-ko/Desktop/projects/udacity/artist_bookings/env/lib/python3.6/site-packages/sqlalchemy/engine/base.py", line 2275, in _wrap_pool_connect
    return fn()
  File "/home/dharmy-ko/Desktop/projects/udacity/artist_bookings/env/lib/python3.6/site-packages/sqlalchemy/pool/base.py", line 363, in connect
    return _ConnectionFairy._checkout(self)
  File "/home/dharmy-ko/Desktop/projects/udacity/artist_bookings/env/lib/python3.6/site-packages/sqlalchemy/pool/base.py", line 760, in _checkout
    fairy = _ConnectionRecord.checkout(pool)
  File "/home/dharmy-ko/Desktop/projects/udacity/artist_bookings/env/lib/python3.6/site-packages/sqlalchemy/pool/base.py", line 492, in checkout
    rec = pool._do_get()
  File "/home/dharmy-ko/Desktop/projects/udacity/artist_bookings/env/lib/python3.6/site-packages/sqlalchemy/pool/impl.py", line 139, in _do_get
    self._dec_overflow()
  File "/home/dharmy-ko/Desktop/projects/udacity/artist_bookings/env/lib/python3.6/site-packages/sqlalchemy/util/langhelpers.py", line 68, in __exit__
    compat.reraise(exc_type, exc_value, exc_tb)
  File "/home/dharmy-ko/Desktop/projects/udacity/artist_bookings/env/lib/python3.6/site-packages/sqlalchemy/util/compat.py", line 153, in reraise
    raise value
  File "/home/dharmy-ko/Desktop/projects/udacity/artist_bookings/env/lib/python3.6/site-packages/sqlalchemy/pool/impl.py", line 136, in _do_get
    return self._create_connection()
  File "/home/dharmy-ko/Desktop/projects/udacity/artist_bookings/env/lib/python3.6/site-packages/sqlalchemy/pool/base.py", line 308, in _create_connection
    return _ConnectionRecord(self)
  File "/home/dharmy-ko/Desktop/projects/udacity/artist_bookings/env/lib/python3.6/site-packages/sqlalchemy/pool/base.py", line 437, in __init__
    self.__connect(first_connect_check=True)
  File "/home/dharmy-ko/Desktop/projects/udacity/artist_bookings/env/lib/python3.6/site-packages/sqlalchemy/pool/base.py", line 639, in __connect
    connection = pool._invoke_creator(self)
  File "/home/dharmy-ko/Desktop/projects/udacity/artist_bookings/env/lib/python3.6/site-packages/sqlalchemy/engine/strategies.py", line 114, in connect
    return dialect.connect(*cargs, **cparams)
  File "/home/dharmy-ko/Desktop/projects/udacity/artist_bookings/env/lib/python3.6/site-packages/sqlalchemy/engine/default.py", line 453, in connect
    return self.dbapi.connect(*cargs, **cparams)
  File "/home/dharmy-ko/Desktop/projects/udacity/artist_bookings/env/lib/python3.6/site-packages/psycopg2/__init__.py", line 126, in connect
    conn = _connect(dsn, connection_factory=connection_factory, **kwasync)
sqlalchemy.exc.OperationalError: (psycopg2.OperationalError) FATAL:  database "fyyur" does not exist

(Background on this error at: http://sqlalche.me/e/e3q8)
2019-10-11 13:48:09,844 ERROR: Exception on /artists [GET] [in /home/dharmy-ko/Desktop/projects/udacity/artist_bookings/env/lib/python3.6/site-packages/flask/app.py:1891]
Traceback (most recent call last):
  File "/home/dharmy-ko/Desktop/projects/udacity/artist_bookings/env/lib/python3.6/site-packages/sqlalchemy/engine/base.py", line 2275, in _wrap_pool_connect
    return fn()
  File "/home/dharmy-ko/Desktop/projects/udacity/artist_bookings/env/lib/python3.6/site-packages/sqlalchemy/pool/base.py", line 363, in connect
    return _ConnectionFairy._checkout(self)
  File "/home/dharmy-ko/Desktop/projects/udacity/artist_bookings/env/lib/python3.6/site-packages/sqlalchemy/pool/base.py", line 760, in _checkout
    fairy = _ConnectionRecord.checkout(pool)
  File "/home/dharmy-ko/Desktop/projects/udacity/artist_bookings/env/lib/python3.6/site-packages/sqlalchemy/pool/base.py", line 492, in checkout
    rec = pool._do_get()
  File "/home/dharmy-ko/Desktop/projects/udacity/artist_bookings/env/lib/python3.6/site-packages/sqlalchemy/pool/impl.py", line 139, in _do_get
    self._dec_overflow()
  File "/home/dharmy-ko/Desktop/projects/udacity/artist_bookings/env/lib/python3.6/site-packages/sqlalchemy/util/langhelpers.py", line 68, in __exit__
    compat.reraise(exc_type, exc_value, exc_tb)
  File "/home/dharmy-ko/Desktop/projects/udacity/artist_bookings/env/lib/python3.6/site-packages/sqlalchemy/util/compat.py", line 153, in reraise
    raise value
  File "/home/dharmy-ko/Desktop/projects/udacity/artist_bookings/env/lib/python3.6/site-packages/sqlalchemy/pool/impl.py", line 136, in _do_get
    return self._create_connection()
  File "/home/dharmy-ko/Desktop/projects/udacity/artist_bookings/env/lib/python3.6/site-packages/sqlalchemy/pool/base.py", line 308, in _create_connection
    return _ConnectionRecord(self)
  File "/home/dharmy-ko/Desktop/projects/udacity/artist_bookings/env/lib/python3.6/site-packages/sqlalchemy/pool/base.py", line 437, in __init__
    self.__connect(first_connect_check=True)
  File "/home/dharmy-ko/Desktop/projects/udacity/artist_bookings/env/lib/python3.6/site-packages/sqlalchemy/pool/base.py", line 639, in __connect
    connection = pool._invoke_creator(self)
  File "/home/dharmy-ko/Desktop/projects/udacity/artist_bookings/env/lib/python3.6/site-packages/sqlalchemy/engine/strategies.py", line 114, in connect
    return dialect.connect(*cargs, **cparams)
  File "/home/dharmy-ko/Desktop/projects/udacity/artist_bookings/env/lib/python3.6/site-packages/sqlalchemy/engine/default.py", line 453, in connect
    return self.dbapi.connect(*cargs, **cparams)
  File "/home/dharmy-ko/Desktop/projects/udacity/artist_bookings/env/lib/python3.6/site-packages/psycopg2/__init__.py", line 126, in connect
    conn = _connect(dsn, connection_factory=connection_factory, **kwasync)
psycopg2.OperationalError: FATAL:  database "fyyur" does not exist


The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/home/dharmy-ko/Desktop/projects/udacity/artist_bookings/env/lib/python3.6/site-packages/flask/app.py", line 2446, in wsgi_app
    response = self.full_dispatch_request()
  File "/home/dharmy-ko/Desktop/projects/udacity/artist_bookings/env/lib/python3.6/site-packages/flask/app.py", line 1951, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/home/dharmy-ko/Desktop/projects/udacity/artist_bookings/env/lib/python3.6/site-packages/flask/app.py", line 1820, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "/home/dharmy-ko/Desktop/projects/udacity/artist_bookings/env/lib/python3.6/site-packages/flask/_compat.py", line 39, in reraise
    raise value
  File "/home/dharmy-ko/Desktop/projects/udacity/artist_bookings/env/lib/python3.6/site-packages/flask/app.py", line 1949, in full_dispatch_request
    rv = self.dispatch_request()
  File "/home/dharmy-ko/Desktop/projects/udacity/artist_bookings/env/lib/python3.6/site-packages/flask/app.py", line 1935, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/home/dharmy-ko/Desktop/projects/udacity/artist_bookings/starter_code/app.py", line 260, in artists
    def search_artists():
  File "/home/dharmy-ko/Desktop/projects/udacity/artist_bookings/env/lib/python3.6/site-packages/sqlalchemy/orm/query.py", line 3178, in all
    return list(self)
  File "/home/dharmy-ko/Desktop/projects/udacity/artist_bookings/env/lib/python3.6/site-packages/sqlalchemy/orm/query.py", line 3334, in __iter__
    return self._execute_and_instances(context)
  File "/home/dharmy-ko/Desktop/projects/udacity/artist_bookings/env/lib/python3.6/site-packages/sqlalchemy/orm/query.py", line 3356, in _execute_and_instances
    querycontext, self._connection_from_session, close_with_result=True
  File "/home/dharmy-ko/Desktop/projects/udacity/artist_bookings/env/lib/python3.6/site-packages/sqlalchemy/orm/query.py", line 3371, in _get_bind_args
    mapper=self._bind_mapper(), clause=querycontext.statement, **kw
  File "/home/dharmy-ko/Desktop/projects/udacity/artist_bookings/env/lib/python3.6/site-packages/sqlalchemy/orm/query.py", line 3349, in _connection_from_session
    conn = self.session.connection(**kw)
  File "/home/dharmy-ko/Desktop/projects/udacity/artist_bookings/env/lib/python3.6/site-packages/sqlalchemy/orm/session.py", line 1124, in connection
    execution_options=execution_options,
  File "/home/dharmy-ko/Desktop/projects/udacity/artist_bookings/env/lib/python3.6/site-packages/sqlalchemy/orm/session.py", line 1130, in _connection_for_bind
    engine, execution_options
  File "/home/dharmy-ko/Desktop/projects/udacity/artist_bookings/env/lib/python3.6/site-packages/sqlalchemy/orm/session.py", line 431, in _connection_for_bind
    conn = bind._contextual_connect()
  File "/home/dharmy-ko/Desktop/projects/udacity/artist_bookings/env/lib/python3.6/site-packages/sqlalchemy/engine/base.py", line 2239, in _contextual_connect
    self._wrap_pool_connect(self.pool.connect, None),
  File "/home/dharmy-ko/Desktop/projects/udacity/artist_bookings/env/lib/python3.6/site-packages/sqlalchemy/engine/base.py", line 2279, in _wrap_pool_connect
    e, dialect, self
  File "/home/dharmy-ko/Desktop/projects/udacity/artist_bookings/env/lib/python3.6/site-packages/sqlalchemy/engine/base.py", line 1544, in _handle_dbapi_exception_noconnection
    util.raise_from_cause(sqlalchemy_exception, exc_info)
  File "/home/dharmy-ko/Desktop/projects/udacity/artist_bookings/env/lib/python3.6/site-packages/sqlalchemy/util/compat.py", line 398, in raise_from_cause
    reraise(type(exception), exception, tb=exc_tb, cause=cause)
  File "/home/dharmy-ko/Desktop/projects/udacity/artist_bookings/env/lib/python3.6/site-packages/sqlalchemy/util/compat.py", line 152, in reraise
    raise value.with_traceback(tb)
  File "/home/dharmy-ko/Desktop/projects/udacity/artist_bookings/env/lib/python3.6/site-packages/sqlalchemy/engine/base.py", line 2275, in _wrap_pool_connect
    return fn()
  File "/home/dharmy-ko/Desktop/projects/udacity/artist_bookings/env/lib/python3.6/site-packages/sqlalchemy/pool/base.py", line 363, in connect
    return _ConnectionFairy._checkout(self)
  File "/home/dharmy-ko/Desktop/projects/udacity/artist_bookings/env/lib/python3.6/site-packages/sqlalchemy/pool/base.py", line 760, in _checkout
    fairy = _ConnectionRecord.checkout(pool)
  File "/home/dharmy-ko/Desktop/projects/udacity/artist_bookings/env/lib/python3.6/site-packages/sqlalchemy/pool/base.py", line 492, in checkout
    rec = pool._do_get()
  File "/home/dharmy-ko/Desktop/projects/udacity/artist_bookings/env/lib/python3.6/site-packages/sqlalchemy/pool/impl.py", line 139, in _do_get
    self._dec_overflow()
  File "/home/dharmy-ko/Desktop/projects/udacity/artist_bookings/env/lib/python3.6/site-packages/sqlalchemy/util/langhelpers.py", line 68, in __exit__
    compat.reraise(exc_type, exc_value, exc_tb)
  File "/home/dharmy-ko/Desktop/projects/udacity/artist_bookings/env/lib/python3.6/site-packages/sqlalchemy/util/compat.py", line 153, in reraise
    raise value
  File "/home/dharmy-ko/Desktop/projects/udacity/artist_bookings/env/lib/python3.6/site-packages/sqlalchemy/pool/impl.py", line 136, in _do_get
    return self._create_connection()
  File "/home/dharmy-ko/Desktop/projects/udacity/artist_bookings/env/lib/python3.6/site-packages/sqlalchemy/pool/base.py", line 308, in _create_connection
    return _ConnectionRecord(self)
  File "/home/dharmy-ko/Desktop/projects/udacity/artist_bookings/env/lib/python3.6/site-packages/sqlalchemy/pool/base.py", line 437, in __init__
    self.__connect(first_connect_check=True)
  File "/home/dharmy-ko/Desktop/projects/udacity/artist_bookings/env/lib/python3.6/site-packages/sqlalchemy/pool/base.py", line 639, in __connect
    connection = pool._invoke_creator(self)
  File "/home/dharmy-ko/Desktop/projects/udacity/artist_bookings/env/lib/python3.6/site-packages/sqlalchemy/engine/strategies.py", line 114, in connect
    return dialect.connect(*cargs, **cparams)
  File "/home/dharmy-ko/Desktop/projects/udacity/artist_bookings/env/lib/python3.6/site-packages/sqlalchemy/engine/default.py", line 453, in connect
    return self.dbapi.connect(*cargs, **cparams)
  File "/home/dharmy-ko/Desktop/projects/udacity/artist_bookings/env/lib/python3.6/site-packages/psycopg2/__init__.py", line 126, in connect
    conn = _connect(dsn, connection_factory=connection_factory, **kwasync)
sqlalchemy.exc.OperationalError: (psycopg2.OperationalError) FATAL:  database "fyyur" does not exist

(Background on this error at: http://sqlalche.me/e/e3q8)
2019-10-11 13:49:01,539 INFO: errors [in /home/dharmy-ko/Desktop/projects/udacity/artist_bookings/starter_code/app.py:548]
2019-10-11 13:49:06,592 ERROR: Exception on /venues [GET] [in /home/dharmy-ko/Desktop/projects/udacity/artist_bookings/env/lib/python3.6/site-packages/flask/app.py:1891]
Traceback (most recent call last):
  File "/home/dharmy-ko/Desktop/projects/udacity/artist_bookings/env/lib/python3.6/site-packages/sqlalchemy/engine/base.py", line 2275, in _wrap_pool_connect
    return fn()
  File "/home/dharmy-ko/Desktop/projects/udacity/artist_bookings/env/lib/python3.6/site-packages/sqlalchemy/pool/base.py", line 363, in connect
    return _ConnectionFairy._checkout(self)
  File "/home/dharmy-ko/Desktop/projects/udacity/artist_bookings/env/lib/python3.6/site-packages/sqlalchemy/pool/base.py", line 760, in _checkout
    fairy = _ConnectionRecord.checkout(pool)
  File "/home/dharmy-ko/Desktop/projects/udacity/artist_bookings/env/lib/python3.6/site-packages/sqlalchemy/pool/base.py", line 492, in checkout
    rec = pool._do_get()
  File "/home/dharmy-ko/Desktop/projects/udacity/artist_bookings/env/lib/python3.6/site-packages/sqlalchemy/pool/impl.py", line 139, in _do_get
    self._dec_overflow()
  File "/home/dharmy-ko/Desktop/projects/udacity/artist_bookings/env/lib/python3.6/site-packages/sqlalchemy/util/langhelpers.py", line 68, in __exit__
    compat.reraise(exc_type, exc_value, exc_tb)
  File "/home/dharmy-ko/Desktop/projects/udacity/artist_bookings/env/lib/python3.6/site-packages/sqlalchemy/util/compat.py", line 153, in reraise
    raise value
  File "/home/dharmy-ko/Desktop/projects/udacity/artist_bookings/env/lib/python3.6/site-packages/sqlalchemy/pool/impl.py", line 136, in _do_get
    return self._create_connection()
  File "/home/dharmy-ko/Desktop/projects/udacity/artist_bookings/env/lib/python3.6/site-packages/sqlalchemy/pool/base.py", line 308, in _create_connection
    return _ConnectionRecord(self)
  File "/home/dharmy-ko/Desktop/projects/udacity/artist_bookings/env/lib/python3.6/site-packages/sqlalchemy/pool/base.py", line 437, in __init__
    self.__connect(first_connect_check=True)
  File "/home/dharmy-ko/Desktop/projects/udacity/artist_bookings/env/lib/python3.6/site-packages/sqlalchemy/pool/base.py", line 639, in __connect
    connection = pool._invoke_creator(self)
  File "/home/dharmy-ko/Desktop/projects/udacity/artist_bookings/env/lib/python3.6/site-packages/sqlalchemy/engine/strategies.py", line 114, in connect
    return dialect.connect(*cargs, **cparams)
  File "/home/dharmy-ko/Desktop/projects/udacity/artist_bookings/env/lib/python3.6/site-packages/sqlalchemy/engine/default.py", line 453, in connect
    return self.dbapi.connect(*cargs, **cparams)
  File "/home/dharmy-ko/Desktop/projects/udacity/artist_bookings/env/lib/python3.6/site-packages/psycopg2/__init__.py", line 126, in connect
    conn = _connect(dsn, connection_factory=connection_factory, **kwasync)
psycopg2.OperationalError: FATAL:  database "fyyur" does not exist


The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/home/dharmy-ko/Desktop/projects/udacity/artist_bookings/env/lib/python3.6/site-packages/flask/app.py", line 2446, in wsgi_app
    response = self.full_dispatch_request()
  File "/home/dharmy-ko/Desktop/projects/udacity/artist_bookings/env/lib/python3.6/site-packages/flask/app.py", line 1951, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/home/dharmy-ko/Desktop/projects/udacity/artist_bookings/env/lib/python3.6/site-packages/flask/app.py", line 1820, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "/home/dharmy-ko/Desktop/projects/udacity/artist_bookings/env/lib/python3.6/site-packages/flask/_compat.py", line 39, in reraise
    raise value
  File "/home/dharmy-ko/Desktop/projects/udacity/artist_bookings/env/lib/python3.6/site-packages/flask/app.py", line 1949, in full_dispatch_request
    rv = self.dispatch_request()
  File "/home/dharmy-ko/Desktop/projects/udacity/artist_bookings/env/lib/python3.6/site-packages/flask/app.py", line 1935, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/home/dharmy-ko/Desktop/projects/udacity/artist_bookings/starter_code/app.py", line 76, in venues
    venues = Venue.query.distinct(Venue.state).all()
  File "/home/dharmy-ko/Desktop/projects/udacity/artist_bookings/env/lib/python3.6/site-packages/sqlalchemy/orm/query.py", line 3178, in all
    return list(self)
  File "/home/dharmy-ko/Desktop/projects/udacity/artist_bookings/env/lib/python3.6/site-packages/sqlalchemy/orm/query.py", line 3334, in __iter__
    return self._execute_and_instances(context)
  File "/home/dharmy-ko/Desktop/projects/udacity/artist_bookings/env/lib/python3.6/site-packages/sqlalchemy/orm/query.py", line 3356, in _execute_and_instances
    querycontext, self._connection_from_session, close_with_result=True
  File "/home/dharmy-ko/Desktop/projects/udacity/artist_bookings/env/lib/python3.6/site-packages/sqlalchemy/orm/query.py", line 3371, in _get_bind_args
    mapper=self._bind_mapper(), clause=querycontext.statement, **kw
  File "/home/dharmy-ko/Desktop/projects/udacity/artist_bookings/env/lib/python3.6/site-packages/sqlalchemy/orm/query.py", line 3349, in _connection_from_session
    conn = self.session.connection(**kw)
  File "/home/dharmy-ko/Desktop/projects/udacity/artist_bookings/env/lib/python3.6/site-packages/sqlalchemy/orm/session.py", line 1124, in connection
    execution_options=execution_options,
  File "/home/dharmy-ko/Desktop/projects/udacity/artist_bookings/env/lib/python3.6/site-packages/sqlalchemy/orm/session.py", line 1130, in _connection_for_bind
    engine, execution_options
  File "/home/dharmy-ko/Desktop/projects/udacity/artist_bookings/env/lib/python3.6/site-packages/sqlalchemy/orm/session.py", line 431, in _connection_for_bind
    conn = bind._contextual_connect()
  File "/home/dharmy-ko/Desktop/projects/udacity/artist_bookings/env/lib/python3.6/site-packages/sqlalchemy/engine/base.py", line 2239, in _contextual_connect
    self._wrap_pool_connect(self.pool.connect, None),
  File "/home/dharmy-ko/Desktop/projects/udacity/artist_bookings/env/lib/python3.6/site-packages/sqlalchemy/engine/base.py", line 2279, in _wrap_pool_connect
    e, dialect, self
  File "/home/dharmy-ko/Desktop/projects/udacity/artist_bookings/env/lib/python3.6/site-packages/sqlalchemy/engine/base.py", line 1544, in _handle_dbapi_exception_noconnection
    util.raise_from_cause(sqlalchemy_exception, exc_info)
  File "/home/dharmy-ko/Desktop/projects/udacity/artist_bookings/env/lib/python3.6/site-packages/sqlalchemy/util/compat.py", line 398, in raise_from_cause
    reraise(type(exception), exception, tb=exc_tb, cause=cause)
  File "/home/dharmy-ko/Desktop/projects/udacity/artist_bookings/env/lib/python3.6/site-packages/sqlalchemy/util/compat.py", line 152, in reraise
    raise value.with_traceback(tb)
  File "/home/dharmy-ko/Desktop/projects/udacity/artist_bookings/env/lib/python3.6/site-packages/sqlalchemy/engine/base.py", line 2275, in _wrap_pool_connect
    return fn()
  File "/home/dharmy-ko/Desktop/projects/udacity/artist_bookings/env/lib/python3.6/site-packages/sqlalchemy/pool/base.py", line 363, in connect
    return _ConnectionFairy._checkout(self)
  File "/home/dharmy-ko/Desktop/projects/udacity/artist_bookings/env/lib/python3.6/site-packages/sqlalchemy/pool/base.py", line 760, in _checkout
    fairy = _ConnectionRecord.checkout(pool)
  File "/home/dharmy-ko/Desktop/projects/udacity/artist_bookings/env/lib/python3.6/site-packages/sqlalchemy/pool/base.py", line 492, in checkout
    rec = pool._do_get()
  File "/home/dharmy-ko/Desktop/projects/udacity/artist_bookings/env/lib/python3.6/site-packages/sqlalchemy/pool/impl.py", line 139, in _do_get
    self._dec_overflow()
  File "/home/dharmy-ko/Desktop/projects/udacity/artist_bookings/env/lib/python3.6/site-packages/sqlalchemy/util/langhelpers.py", line 68, in __exit__
    compat.reraise(exc_type, exc_value, exc_tb)
  File "/home/dharmy-ko/Desktop/projects/udacity/artist_bookings/env/lib/python3.6/site-packages/sqlalchemy/util/compat.py", line 153, in reraise
    raise value
  File "/home/dharmy-ko/Desktop/projects/udacity/artist_bookings/env/lib/python3.6/site-packages/sqlalchemy/pool/impl.py", line 136, in _do_get
    return self._create_connection()
  File "/home/dharmy-ko/Desktop/projects/udacity/artist_bookings/env/lib/python3.6/site-packages/sqlalchemy/pool/base.py", line 308, in _create_connection
    return _ConnectionRecord(self)
  File "/home/dharmy-ko/Desktop/projects/udacity/artist_bookings/env/lib/python3.6/site-packages/sqlalchemy/pool/base.py", line 437, in __init__
    self.__connect(first_connect_check=True)
  File "/home/dharmy-ko/Desktop/projects/udacity/artist_bookings/env/lib/python3.6/site-packages/sqlalchemy/pool/base.py", line 639, in __connect
    connection = pool._invoke_creator(self)
  File "/home/dharmy-ko/Desktop/projects/udacity/artist_bookings/env/lib/python3.6/site-packages/sqlalchemy/engine/strategies.py", line 114, in connect
    return dialect.connect(*cargs, **cparams)
  File "/home/dharmy-ko/Desktop/projects/udacity/artist_bookings/env/lib/python3.6/site-packages/sqlalchemy/engine/default.py", line 453, in connect
    return self.dbapi.connect(*cargs, **cparams)
  File "/home/dharmy-ko/Desktop/projects/udacity/artist_bookings/env/lib/python3.6/site-packages/psycopg2/__init__.py", line 126, in connect
    conn = _connect(dsn, connection_factory=connection_factory, **kwasync)
sqlalchemy.exc.OperationalError: (psycopg2.OperationalError) FATAL:  database "fyyur" does not exist

(Background on this error at: http://sqlalche.me/e/e3q8)
2019-10-11 13:49:16,312 ERROR: Exception on /artists [GET] [in /home/dharmy-ko/Desktop/projects/udacity/artist_bookings/env/lib/python3.6/site-packages/flask/app.py:1891]
Traceback (most recent call last):
  File "/home/dharmy-ko/Desktop/projects/udacity/artist_bookings/env/lib/python3.6/site-packages/sqlalchemy/engine/base.py", line 2275, in _wrap_pool_connect
    return fn()
  File "/home/dharmy-ko/Desktop/projects/udacity/artist_bookings/env/lib/python3.6/site-packages/sqlalchemy/pool/base.py", line 363, in connect
    return _ConnectionFairy._checkout(self)
  File "/home/dharmy-ko/Desktop/projects/udacity/artist_bookings/env/lib/python3.6/site-packages/sqlalchemy/pool/base.py", line 760, in _checkout
    fairy = _ConnectionRecord.checkout(pool)
  File "/home/dharmy-ko/Desktop/projects/udacity/artist_bookings/env/lib/python3.6/site-packages/sqlalchemy/pool/base.py", line 492, in checkout
    rec = pool._do_get()
  File "/home/dharmy-ko/Desktop/projects/udacity/artist_bookings/env/lib/python3.6/site-packages/sqlalchemy/pool/impl.py", line 139, in _do_get
    self._dec_overflow()
  File "/home/dharmy-ko/Desktop/projects/udacity/artist_bookings/env/lib/python3.6/site-packages/sqlalchemy/util/langhelpers.py", line 68, in __exit__
    compat.reraise(exc_type, exc_value, exc_tb)
  File "/home/dharmy-ko/Desktop/projects/udacity/artist_bookings/env/lib/python3.6/site-packages/sqlalchemy/util/compat.py", line 153, in reraise
    raise value
  File "/home/dharmy-ko/Desktop/projects/udacity/artist_bookings/env/lib/python3.6/site-packages/sqlalchemy/pool/impl.py", line 136, in _do_get
    return self._create_connection()
  File "/home/dharmy-ko/Desktop/projects/udacity/artist_bookings/env/lib/python3.6/site-packages/sqlalchemy/pool/base.py", line 308, in _create_connection
    return _ConnectionRecord(self)
  File "/home/dharmy-ko/Desktop/projects/udacity/artist_bookings/env/lib/python3.6/site-packages/sqlalchemy/pool/base.py", line 437, in __init__
    self.__connect(first_connect_check=True)
  File "/home/dharmy-ko/Desktop/projects/udacity/artist_bookings/env/lib/python3.6/site-packages/sqlalchemy/pool/base.py", line 639, in __connect
    connection = pool._invoke_creator(self)
  File "/home/dharmy-ko/Desktop/projects/udacity/artist_bookings/env/lib/python3.6/site-packages/sqlalchemy/engine/strategies.py", line 114, in connect
    return dialect.connect(*cargs, **cparams)
  File "/home/dharmy-ko/Desktop/projects/udacity/artist_bookings/env/lib/python3.6/site-packages/sqlalchemy/engine/default.py", line 453, in connect
    return self.dbapi.connect(*cargs, **cparams)
  File "/home/dharmy-ko/Desktop/projects/udacity/artist_bookings/env/lib/python3.6/site-packages/psycopg2/__init__.py", line 126, in connect
    conn = _connect(dsn, connection_factory=connection_factory, **kwasync)
psycopg2.OperationalError: FATAL:  database "fyyur" does not exist


The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/home/dharmy-ko/Desktop/projects/udacity/artist_bookings/env/lib/python3.6/site-packages/flask/app.py", line 2446, in wsgi_app
    response = self.full_dispatch_request()
  File "/home/dharmy-ko/Desktop/projects/udacity/artist_bookings/env/lib/python3.6/site-packages/flask/app.py", line 1951, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/home/dharmy-ko/Desktop/projects/udacity/artist_bookings/env/lib/python3.6/site-packages/flask/app.py", line 1820, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "/home/dharmy-ko/Desktop/projects/udacity/artist_bookings/env/lib/python3.6/site-packages/flask/_compat.py", line 39, in reraise
    raise value
  File "/home/dharmy-ko/Desktop/projects/udacity/artist_bookings/env/lib/python3.6/site-packages/flask/app.py", line 1949, in full_dispatch_request
    rv = self.dispatch_request()
  File "/home/dharmy-ko/Desktop/projects/udacity/artist_bookings/env/lib/python3.6/site-packages/flask/app.py", line 1935, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/home/dharmy-ko/Desktop/projects/udacity/artist_bookings/starter_code/app.py", line 257, in artists
    data = Artist.query.all()
  File "/home/dharmy-ko/Desktop/projects/udacity/artist_bookings/env/lib/python3.6/site-packages/sqlalchemy/orm/query.py", line 3178, in all
    return list(self)
  File "/home/dharmy-ko/Desktop/projects/udacity/artist_bookings/env/lib/python3.6/site-packages/sqlalchemy/orm/query.py", line 3334, in __iter__
    return self._execute_and_instances(context)
  File "/home/dharmy-ko/Desktop/projects/udacity/artist_bookings/env/lib/python3.6/site-packages/sqlalchemy/orm/query.py", line 3356, in _execute_and_instances
    querycontext, self._connection_from_session, close_with_result=True
  File "/home/dharmy-ko/Desktop/projects/udacity/artist_bookings/env/lib/python3.6/site-packages/sqlalchemy/orm/query.py", line 3371, in _get_bind_args
    mapper=self._bind_mapper(), clause=querycontext.statement, **kw
  File "/home/dharmy-ko/Desktop/projects/udacity/artist_bookings/env/lib/python3.6/site-packages/sqlalchemy/orm/query.py", line 3349, in _connection_from_session
    conn = self.session.connection(**kw)
  File "/home/dharmy-ko/Desktop/projects/udacity/artist_bookings/env/lib/python3.6/site-packages/sqlalchemy/orm/session.py", line 1124, in connection
    execution_options=execution_options,
  File "/home/dharmy-ko/Desktop/projects/udacity/artist_bookings/env/lib/python3.6/site-packages/sqlalchemy/orm/session.py", line 1130, in _connection_for_bind
    engine, execution_options
  File "/home/dharmy-ko/Desktop/projects/udacity/artist_bookings/env/lib/python3.6/site-packages/sqlalchemy/orm/session.py", line 431, in _connection_for_bind
    conn = bind._contextual_connect()
  File "/home/dharmy-ko/Desktop/projects/udacity/artist_bookings/env/lib/python3.6/site-packages/sqlalchemy/engine/base.py", line 2239, in _contextual_connect
    self._wrap_pool_connect(self.pool.connect, None),
  File "/home/dharmy-ko/Desktop/projects/udacity/artist_bookings/env/lib/python3.6/site-packages/sqlalchemy/engine/base.py", line 2279, in _wrap_pool_connect
    e, dialect, self
  File "/home/dharmy-ko/Desktop/projects/udacity/artist_bookings/env/lib/python3.6/site-packages/sqlalchemy/engine/base.py", line 1544, in _handle_dbapi_exception_noconnection
    util.raise_from_cause(sqlalchemy_exception, exc_info)
  File "/home/dharmy-ko/Desktop/projects/udacity/artist_bookings/env/lib/python3.6/site-packages/sqlalchemy/util/compat.py", line 398, in raise_from_cause
    reraise(type(exception), exception, tb=exc_tb, cause=cause)
  File "/home/dharmy-ko/Desktop/projects/udacity/artist_bookings/env/lib/python3.6/site-packages/sqlalchemy/util/compat.py", line 152, in reraise
    raise value.with_traceback(tb)
  File "/home/dharmy-ko/Desktop/projects/udacity/artist_bookings/env/lib/python3.6/site-packages/sqlalchemy/engine/base.py", line 2275, in _wrap_pool_connect
    return fn()
  File "/home/dharmy-ko/Desktop/projects/udacity/artist_bookings/env/lib/python3.6/site-packages/sqlalchemy/pool/base.py", line 363, in connect
    return _ConnectionFairy._checkout(self)
  File "/home/dharmy-ko/Desktop/projects/udacity/artist_bookings/env/lib/python3.6/site-packages/sqlalchemy/pool/base.py", line 760, in _checkout
    fairy = _ConnectionRecord.checkout(pool)
  File "/home/dharmy-ko/Desktop/projects/udacity/artist_bookings/env/lib/python3.6/site-packages/sqlalchemy/pool/base.py", line 492, in checkout
    rec = pool._do_get()
  File "/home/dharmy-ko/Desktop/projects/udacity/artist_bookings/env/lib/python3.6/site-packages/sqlalchemy/pool/impl.py", line 139, in _do_get
    self._dec_overflow()
  File "/home/dharmy-ko/Desktop/projects/udacity/artist_bookings/env/lib/python3.6/site-packages/sqlalchemy/util/langhelpers.py", line 68, in __exit__
    compat.reraise(exc_type, exc_value, exc_tb)
  File "/home/dharmy-ko/Desktop/projects/udacity/artist_bookings/env/lib/python3.6/site-packages/sqlalchemy/util/compat.py", line 153, in reraise
    raise value
  File "/home/dharmy-ko/Desktop/projects/udacity/artist_bookings/env/lib/python3.6/site-packages/sqlalchemy/pool/impl.py", line 136, in _do_get
    return self._create_connection()
  File "/home/dharmy-ko/Desktop/projects/udacity/artist_bookings/env/lib/python3.6/site-packages/sqlalchemy/pool/base.py", line 308, in _create_connection
    return _ConnectionRecord(self)
  File "/home/dharmy-ko/Desktop/projects/udacity/artist_bookings/env/lib/python3.6/site-packages/sqlalchemy/pool/base.py", line 437, in __init__
    self.__connect(first_connect_check=True)
  File "/home/dharmy-ko/Desktop/projects/udacity/artist_bookings/env/lib/python3.6/site-packages/sqlalchemy/pool/base.py", line 639, in __connect
    connection = pool._invoke_creator(self)
  File "/home/dharmy-ko/Desktop/projects/udacity/artist_bookings/env/lib/python3.6/site-packages/sqlalchemy/engine/strategies.py", line 114, in connect
    return dialect.connect(*cargs, **cparams)
  File "/home/dharmy-ko/Desktop/projects/udacity/artist_bookings/env/lib/python3.6/site-packages/sqlalchemy/engine/default.py", line 453, in connect
    return self.dbapi.connect(*cargs, **cparams)
  File "/home/dharmy-ko/Desktop/projects/udacity/artist_bookings/env/lib/python3.6/site-packages/psycopg2/__init__.py", line 126, in connect
    conn = _connect(dsn, connection_factory=connection_factory, **kwasync)
sqlalchemy.exc.OperationalError: (psycopg2.OperationalError) FATAL:  database "fyyur" does not exist

(Background on this error at: http://sqlalche.me/e/e3q8)
2019-10-11 13:55:14,690 INFO: errors [in /home/dharmy-ko/Desktop/projects/udacity/artist_bookings/starter_code/app.py:548]
2019-10-11 13:55:25,100 INFO: errors [in /home/dharmy-ko/Desktop/projects/udacity/artist_bookings/starter_code/app.py:548]
